#version: '3.8'

services:
  free5gc-upf:
    container_name: upf
    user: "${UID_GID}"
    image: local-free5gc/upf:local-free5gc
    command: bash -c "./upf-iptables.sh && ./upf -c ./config/upfcfg.yaml"
    volumes:
      - ./config/upfcfg.yaml:/free5gc/config/upfcfg.yaml
      - ./config/upf-iptables.sh:/free5gc/upf-iptables.sh
      - ./coverage/upf:/free5gc/coverage/upf
    cap_add:
      - NET_ADMIN
    networks:
      privnet:
        ipv4_address: 10.100.200.2
        aliases:
          - upf.free5gc.org

  db:
    container_name: mongodb
    #    user: "${UID_GID}" TODO: This seems to need root?
    image: mongo
    command: mongod --port 27017
    expose:
      - "27017"
    volumes:
      - dbdata:/data/db
    networks:
      privnet:
        ipv4_address: 10.100.200.3
        aliases:
          - db

  free5gc-nrf:
    container_name: nrf
    user: "${UID_GID}"
    image: local-free5gc/nrf:local-free5gc
    command: ./nrf -c ./config/nrfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/nrfcfg.yaml:/free5gc/config/nrfcfg.yaml
      - ./coverage/nrf:/free5gc/coverage/nrf
      - ./base/free5gc:/go/src/free5gc:r
    environment:
      DB_URI: mongodb://db/free5gc
      GIN_MODE: release
      GOCOVERDIR: /free5gc/coverage/nrf
    networks:
      privnet:
        ipv4_address: 10.100.200.4
        aliases:
          - nrf.free5gc.org
    depends_on:
      - db

  free5gc-amf:
    container_name: amf
    user: "${UID_GID}"
    image: local-free5gc/amf:local-free5gc
    command: ./amf -c ./config/amfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/amfcfg.yaml:/free5gc/config/amfcfg.yaml
      - ./coverage/amf:/free5gc/coverage/amf
      - ./base/free5gc:/go/src/free5gc:r
    environment:
      GIN_MODE: release
      GOCOVERDIR: /free5gc/coverage/amf
    networks:
      privnet:
        ipv4_address: 10.100.200.5
        aliases:
          - amf.free5gc.org
    depends_on:
      - free5gc-nrf

  free5gc-ausf:
    container_name: ausf
    user: "${UID_GID}"
    image: local-free5gc/ausf:local-free5gc
    command: ./ausf -c ./config/ausfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/ausfcfg.yaml:/free5gc/config/ausfcfg.yaml
      - ./coverage/ausf:/free5gc/coverage/ausf
      - ./base/free5gc:/go/src/free5gc:r
    environment:
      GIN_MODE: release
      GOCOVERDIR: /free5gc/coverage/ausf
    networks:
      privnet:
        ipv4_address: 10.100.200.6
        aliases:
          - ausf.free5gc.org
    depends_on:
      - free5gc-nrf

  free5gc-nssf:
    container_name: nssf
    user: "${UID_GID}"
    image: local-free5gc/nssf:local-free5gc
    command: ./nssf -c ./config/nssfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/nssfcfg.yaml:/free5gc/config/nssfcfg.yaml
      - ./coverage/nssf:/free5gc/coverage/nssf
      - ./base/free5gc:/go/src/free5gc:r
    environment:
      GIN_MODE: release
      GOCOVERDIR: /free5gc/coverage/nssf
    networks:
      privnet:
        ipv4_address: 10.100.200.7
        aliases:
          - nssf.free5gc.org
    depends_on:
      - free5gc-nrf

  free5gc-pcf:
    container_name: pcf
    user: "${UID_GID}"
    image: local-free5gc/pcf:local-free5gc
    command: ./pcf -c ./config/pcfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/pcfcfg.yaml:/free5gc/config/pcfcfg.yaml
      - ./coverage/pcf:/free5gc/coverage/pcf
      - ./base/free5gc:/go/src/free5gc:r
    environment:
      GIN_MODE: release
      GOCOVERDIR: /free5gc/coverage/pcf
    networks:
      privnet:
        ipv4_address: 10.100.200.8
        aliases:
          - pcf.free5gc.org
    depends_on:
      - free5gc-nrf

  free5gc-smf:
    container_name: smf
    user: "${UID_GID}"
    image: local-free5gc/smf:local-free5gc
    command: ./smf -c ./config/smfcfg.yaml -u ./config/uerouting.yaml
    expose:
      - "8000"
    volumes:
      - ./config/smfcfg.yaml:/free5gc/config/smfcfg.yaml
      - ./config/uerouting.yaml:/free5gc/config/uerouting.yaml
      - ./coverage/smf:/free5gc/coverage/smf
      - ./base/free5gc:/go/src/free5gc:r
    environment:
      GIN_MODE: release
      GOCOVERDIR: /free5gc/coverage/smf
    networks:
      privnet:
        ipv4_address: 10.100.200.9
        aliases:
          - smf.free5gc.org
    depends_on:
      - free5gc-nrf
      - free5gc-upf

  free5gc-udm:
    container_name: udm
    user: "${UID_GID}"
    image: local-free5gc/udm:local-free5gc
    command: ./udm -c ./config/udmcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/udmcfg.yaml:/free5gc/config/udmcfg.yaml
      - ./coverage/udm:/free5gc/coverage/udm
      - ./base/free5gc:/go/src/free5gc:r
    environment:
      GIN_MODE: release
      GOCOVERDIR: /free5gc/coverage/udm
    networks:
      privnet:
        ipv4_address: 10.100.200.10
        aliases:
          - udm.free5gc.org
    depends_on:
      - db
      - free5gc-nrf

  free5gc-udr:
    container_name: udr
    user: "${UID_GID}"
    image: local-free5gc/udr:local-free5gc
    command: ./udr -c ./config/udrcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/udrcfg.yaml:/free5gc/config/udrcfg.yaml
      - ./coverage/udr:/free5gc/coverage/udr
      - ./base/free5gc:/go/src/free5gc:r
    environment:
      DB_URI: mongodb://db/free5gc
      GIN_MODE: release
      GOCOVERDIR: /free5gc/coverage/udr
    networks:
      privnet:
        ipv4_address: 10.100.200.11
        aliases:
          - udr.free5gc.org
    depends_on:
      - db
      - free5gc-nrf

  free5gc-chf:
    container_name: chf
    user: "${UID_GID}"
    image: local-free5gc/chf:local-free5gc
    command: ./chf -c ./config/chfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/chfcfg.yaml:/free5gc/config/chfcfg.yaml
      - ./coverage/chf:/free5gc/coverage/chf
      - ./base/free5gc:/go/src/free5gc:r
    environment:
      DB_URI: mongodb://db/free5gc
      GIN_MODE: release
      GOCOVERDIR: /free5gc/coverage/chf
    networks:
      privnet:
        ipv4_address: 10.100.200.12
        aliases:
          - chf.free5gc.org
    depends_on:
      - db
      - free5gc-nrf
      - free5gc-webui

  free5gc-n3iwf:
    container_name: n3iwf
    user: "${UID_GID}"
    image: local-free5gc/n3iwf:local-free5gc
    command: sh -c "./n3iwf-ipsec.sh && ./n3iwf -c ./config/n3iwfcfg.yaml"
    volumes:
      - ./config/n3iwfcfg.yaml:/free5gc/config/n3iwfcfg.yaml
      - ./config/n3iwf-ipsec.sh:/free5gc/n3iwf-ipsec.sh
      - ./coverage/n3iwf:/free5gc/coverage/n3iwf
      - ./base/free5gc:/go/src/free5gc:r
    environment:
      GIN_MODE: release
      GOCOVERDIR: /free5gc/coverage/n3iwf
    cap_add:
      - NET_ADMIN
    networks:
      privnet:
        ipv4_address: 10.100.200.13
        aliases:
          - n3iwf.free5gc.org
    depends_on:
      - free5gc-amf
      - free5gc-smf
      - free5gc-upf

  free5gc-webui:
    container_name: webui
    user: "${UID_GID}"
    image: local-free5gc/webui:local-free5gc
    command: ./webui -c ./config/webuicfg.yaml
    expose:
      - "2122"
      - "2121"
    volumes:
      - ./config/webuicfg.yaml:/free5gc/config/webuicfg.yaml
      - ./coverage/webui:/free5gc/coverage/webui
      - ./base/free5gc:/go/src/free5gc:r
    environment:
      GIN_MODE: release
      GOCOVERDIR: /free5gc/coverage/webui
    networks:
      privnet:
        ipv4_address: 10.100.200.14
        aliases:
          - webui
    ports:
      - "5000:5000"
      - "2122:2122"
      - "2121:2121"
    depends_on:
      - db
      - free5gc-nrf

  ueransim:
    container_name: ueransim
    user: "${UID_GID}"
    image: local-free5gc/ueransim:latest
    command: ./nr-gnb -c ./config/gnbcfg.yaml
    volumes:
      - ./config/gnbcfg.yaml:/ueransim/config/gnbcfg.yaml
      - ./config/uecfg.yaml:/ueransim/config/uecfg.yaml
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    networks:
      privnet:
        ipv4_address: 10.100.200.15
        aliases:
          - gnb.free5gc.org
    depends_on:
      - free5gc-amf
      - free5gc-upf

  n3iwue:
    container_name: n3iwue
    image: free5gc/n3iwue:latest
    command: sleep infinity
    volumes:
      - ./config/n3uecfg.yaml:/n3iwue/config/n3ue.yaml
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    networks:
      privnet:
        ipv4_address: 10.100.200.16
        aliases:
          - n3ue.free5gc.org
    depends_on:
      - free5gc-n3iwf

networks:
  privnet:
    ipam:
      driver: default
      config:
        - subnet: 10.100.200.0/24
    driver_opts:
      com.docker.network.bridge.name: br-free5gc

volumes:
  dbdata:
